spring.application.name=MindSolutionsSpring

spring.config.import=optional:file:./.env[.properties]

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.error.include-stacktrace=never
spring.devtools.restart.enabled=false

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

spring.datasource.hikari.connection-init-sql=SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci

spring.mvc.hiddenmethod.filter.enabled=false
spring.mvc.formcontent.filter.enabled=false

spring.web.locale-resolver=fixed
spring.web.locale=es_ES

spring.thymeleaf.cache=false

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.force-request=true
server.servlet.encoding.force-response=true

server.tomcat.uri-encoding=UTF-8

spring.ai.openai.api-key=${AI_API_KEY}
spring.ai.openai.base-url=${AI_API_URL:https://api.openai.com}
spring.ai.openai.embedding.options.model=${AI_EMBEDDING_MODEL:text-embedding-3-small}

spring.ai.openai.chat.options.model =${AI_MODEL:gpt-5-mini}
spring.ai.openai.chat.options.temperature = 1

knowledge.similarity-threshold=0.5
knowledge.top-k=4
knowledge.store-file=knowledge-store.json

project.jwt.key=${JWT_KEY}
project.jwt.expiration=${JWT_EXPIRATION}
